apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devo-carre-local
  namespace: argocd
spec:
  description: Local kind learning project for Devo Carre and its observability stack.
  sourceRepos:
    - https://github.com/badereddinkhmila/kata-carrefour.git
  destinations:
    - namespace: devoteam
      server: https://kubernetes.default.svc
    - namespace: devo-carre-observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
