apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devo-carre-observability
  namespace: argocd
spec:
  project: devo-carre-local
  source:
    repoURL: https://github.com/badereddinkhmila/kata-carrefour.git
    targetRevision: main
    path: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: devo-carre-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
